/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveImageApiClient);
  }
}(this, function(expect, CloudmersiveImageApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveImageApiClient.DetectedLicensePlate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetectedLicensePlate', function() {
    it('should create an instance of DetectedLicensePlate', function() {
      // uncomment below and update the code to test DetectedLicensePlate
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be.a(CloudmersiveImageApiClient.DetectedLicensePlate);
    });

    it('should have the property licensePlateTextBestMatch (base name: "LicensePlateText_BestMatch")', function() {
      // uncomment below and update the code to test the property licensePlateTextBestMatch
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property licensePlateTextRunnerUp (base name: "LicensePlateText_RunnerUp")', function() {
      // uncomment below and update the code to test the property licensePlateTextRunnerUp
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property locationX (base name: "LocationX")', function() {
      // uncomment below and update the code to test the property locationX
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property locationY (base name: "LocationY")', function() {
      // uncomment below and update the code to test the property locationY
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "Width")', function() {
      // uncomment below and update the code to test the property width
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "Height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

    it('should have the property licensePlateRecognitionConfidenceLevel (base name: "LicensePlateRecognitionConfidenceLevel")', function() {
      // uncomment below and update the code to test the property licensePlateRecognitionConfidenceLevel
      //var instane = new CloudmersiveImageApiClient.DetectedLicensePlate();
      //expect(instance).to.be();
    });

  });

}));
