/**
 * imageapi
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveImageApiClient);
  }
}(this, function(expect, CloudmersiveImageApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveImageApiClient.NsfwAdvancedResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NsfwAdvancedResult', function() {
    it('should create an instance of NsfwAdvancedResult', function() {
      // uncomment below and update the code to test NsfwAdvancedResult
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be.a(CloudmersiveImageApiClient.NsfwAdvancedResult);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property cleanResult (base name: "CleanResult")', function() {
      // uncomment below and update the code to test the property cleanResult
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsNudity (base name: "ContainsNudity")', function() {
      // uncomment below and update the code to test the property containsNudity
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsGraphicViolence (base name: "ContainsGraphicViolence")', function() {
      // uncomment below and update the code to test the property containsGraphicViolence
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsNonGraphicViolence (base name: "ContainsNonGraphicViolence")', function() {
      // uncomment below and update the code to test the property containsNonGraphicViolence
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsSelfHarm (base name: "ContainsSelfHarm")', function() {
      // uncomment below and update the code to test the property containsSelfHarm
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsHate (base name: "ContainsHate")', function() {
      // uncomment below and update the code to test the property containsHate
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsPotentialIllegalActivity (base name: "ContainsPotentialIllegalActivity")', function() {
      // uncomment below and update the code to test the property containsPotentialIllegalActivity
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsMedicalImagery (base name: "ContainsMedicalImagery")', function() {
      // uncomment below and update the code to test the property containsMedicalImagery
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property containsProfanity (base name: "ContainsProfanity")', function() {
      // uncomment below and update the code to test the property containsProfanity
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "Score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

    it('should have the property classificationOutcome (base name: "ClassificationOutcome")', function() {
      // uncomment below and update the code to test the property classificationOutcome
      //var instane = new CloudmersiveImageApiClient.NsfwAdvancedResult();
      //expect(instance).to.be();
    });

  });

}));
