/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveImageApiClient);
  }
}(this, function(expect, CloudmersiveImageApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveImageApiClient.ConvertApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConvertApi', function() {
    describe('convertToBmp', function() {
      it('should call convertToBmp successfully', function(done) {
        //uncomment below and update the code to test convertToBmp
        //instance.convertToBmp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToGif', function() {
      it('should call convertToGif successfully', function(done) {
        //uncomment below and update the code to test convertToGif
        //instance.convertToGif(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToJpg', function() {
      it('should call convertToJpg successfully', function(done) {
        //uncomment below and update the code to test convertToJpg
        //instance.convertToJpg(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToPhotoshop', function() {
      it('should call convertToPhotoshop successfully', function(done) {
        //uncomment below and update the code to test convertToPhotoshop
        //instance.convertToPhotoshop(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToPng', function() {
      it('should call convertToPng successfully', function(done) {
        //uncomment below and update the code to test convertToPng
        //instance.convertToPng(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToTiff', function() {
      it('should call convertToTiff successfully', function(done) {
        //uncomment below and update the code to test convertToTiff
        //instance.convertToTiff(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('convertToWebP', function() {
      it('should call convertToWebP successfully', function(done) {
        //uncomment below and update the code to test convertToWebP
        //instance.convertToWebP(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
