/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PolygonPoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PolygonPoint'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveImageApiClient) {
      root.CloudmersiveImageApiClient = {};
    }
    root.CloudmersiveImageApiClient.DrawPolygonInstance = factory(root.CloudmersiveImageApiClient.ApiClient, root.CloudmersiveImageApiClient.PolygonPoint);
  }
}(this, function(ApiClient, PolygonPoint) {
  'use strict';




  /**
   * The DrawPolygonInstance model module.
   * @module model/DrawPolygonInstance
   * @version 1.3.5
   */

  /**
   * Constructs a new <code>DrawPolygonInstance</code>.
   * Polygon instance to draw on an image
   * @alias module:model/DrawPolygonInstance
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DrawPolygonInstance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DrawPolygonInstance} obj Optional instance to populate.
   * @return {module:model/DrawPolygonInstance} The populated <code>DrawPolygonInstance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BorderColor')) {
        obj['BorderColor'] = ApiClient.convertToType(data['BorderColor'], 'String');
      }
      if (data.hasOwnProperty('BorderWidth')) {
        obj['BorderWidth'] = ApiClient.convertToType(data['BorderWidth'], 'Number');
      }
      if (data.hasOwnProperty('FillColor')) {
        obj['FillColor'] = ApiClient.convertToType(data['FillColor'], 'String');
      }
      if (data.hasOwnProperty('Points')) {
        obj['Points'] = ApiClient.convertToType(data['Points'], [PolygonPoint]);
      }
    }
    return obj;
  }

  /**
   * Border Color to use - can be a hex value (with #) or HTML common color name.  Transparent colors are supported.
   * @member {String} BorderColor
   */
  exports.prototype['BorderColor'] = undefined;
  /**
   * Width in pixels of the border.  Pass in 0 to draw a polygon with no border
   * @member {Number} BorderWidth
   */
  exports.prototype['BorderWidth'] = undefined;
  /**
   * Fill Color to use - can be a hex value (with #) or HTML common color name.  Transparent colors are supported.  Leave blank to not fill the polygon.
   * @member {String} FillColor
   */
  exports.prototype['FillColor'] = undefined;
  /**
   * Points (vertices) which comprise the polygon; valid polygons must have at least 3 points
   * @member {Array.<module:model/PolygonPoint>} Points
   */
  exports.prototype['Points'] = undefined;



  return exports;
}));


