/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveImageApiClient) {
      root.CloudmersiveImageApiClient = {};
    }
    root.CloudmersiveImageApiClient.FineTextItem = factory(root.CloudmersiveImageApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FineTextItem model module.
   * @module model/FineTextItem
   * @version 1.3.5
   */

  /**
   * Constructs a new <code>FineTextItem</code>.
   * Individual instance of text occuring in an image; one piece of text
   * @alias module:model/FineTextItem
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>FineTextItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FineTextItem} obj Optional instance to populate.
   * @return {module:model/FineTextItem} The populated <code>FineTextItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TopLeftX')) {
        obj['TopLeftX'] = ApiClient.convertToType(data['TopLeftX'], 'Number');
      }
      if (data.hasOwnProperty('TopLeftY')) {
        obj['TopLeftY'] = ApiClient.convertToType(data['TopLeftY'], 'Number');
      }
      if (data.hasOwnProperty('TopRightX')) {
        obj['TopRightX'] = ApiClient.convertToType(data['TopRightX'], 'Number');
      }
      if (data.hasOwnProperty('TopRightY')) {
        obj['TopRightY'] = ApiClient.convertToType(data['TopRightY'], 'Number');
      }
      if (data.hasOwnProperty('BottomLeftX')) {
        obj['BottomLeftX'] = ApiClient.convertToType(data['BottomLeftX'], 'Number');
      }
      if (data.hasOwnProperty('BottomLeftY')) {
        obj['BottomLeftY'] = ApiClient.convertToType(data['BottomLeftY'], 'Number');
      }
      if (data.hasOwnProperty('BottomRightX')) {
        obj['BottomRightX'] = ApiClient.convertToType(data['BottomRightX'], 'Number');
      }
      if (data.hasOwnProperty('BottomRightY')) {
        obj['BottomRightY'] = ApiClient.convertToType(data['BottomRightY'], 'Number');
      }
      if (data.hasOwnProperty('Width')) {
        obj['Width'] = ApiClient.convertToType(data['Width'], 'Number');
      }
      if (data.hasOwnProperty('Height')) {
        obj['Height'] = ApiClient.convertToType(data['Height'], 'Number');
      }
      if (data.hasOwnProperty('Angle')) {
        obj['Angle'] = ApiClient.convertToType(data['Angle'], 'Number');
      }
    }
    return obj;
  }

  /**
   * X coordinate of the top/left text location; 0 represents the left edge of the input image
   * @member {Number} TopLeftX
   */
  exports.prototype['TopLeftX'] = undefined;
  /**
   * Y coordinate of the top/left text location; 0 represents the top edge of the input image
   * @member {Number} TopLeftY
   */
  exports.prototype['TopLeftY'] = undefined;
  /**
   * X coordinate of the top/right text location; 0 represents the left edge of the input image
   * @member {Number} TopRightX
   */
  exports.prototype['TopRightX'] = undefined;
  /**
   * Y coordinate of the top/right text location; 0 represents the top edge of the input image
   * @member {Number} TopRightY
   */
  exports.prototype['TopRightY'] = undefined;
  /**
   * X coordinate of the bottom/left text location; 0 represents the left edge of the input image
   * @member {Number} BottomLeftX
   */
  exports.prototype['BottomLeftX'] = undefined;
  /**
   * Y coordinate of the bottom/left text location; 0 represents the top edge of the input image
   * @member {Number} BottomLeftY
   */
  exports.prototype['BottomLeftY'] = undefined;
  /**
   * X coordinate of the bottom/right text location; 0 represents the left edge of the input image
   * @member {Number} BottomRightX
   */
  exports.prototype['BottomRightX'] = undefined;
  /**
   * Y coordinate of the bottom/right text location; 0 represents the top edge of the input image
   * @member {Number} BottomRightY
   */
  exports.prototype['BottomRightY'] = undefined;
  /**
   * Width in pixels of the text
   * @member {Number} Width
   */
  exports.prototype['Width'] = undefined;
  /**
   * Height in pixels of the text
   * @member {Number} Height
   */
  exports.prototype['Height'] = undefined;
  /**
   * Rotation Angle in radians of the text
   * @member {Number} Angle
   */
  exports.prototype['Angle'] = undefined;



  return exports;
}));


