/**
 * imageapi
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveImageApiClient) {
      root.CloudmersiveImageApiClient = {};
    }
    root.CloudmersiveImageApiClient.ImageAiDetectionResult = factory(root.CloudmersiveImageApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageAiDetectionResult model module.
   * @module model/ImageAiDetectionResult
   * @version 1.4.0
   */

  /**
   * Constructs a new <code>ImageAiDetectionResult</code>.
   * Result of performing an AI Image detection
   * @alias module:model/ImageAiDetectionResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ImageAiDetectionResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageAiDetectionResult} obj Optional instance to populate.
   * @return {module:model/ImageAiDetectionResult} The populated <code>ImageAiDetectionResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CleanResult')) {
        obj['CleanResult'] = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      }
      if (data.hasOwnProperty('AiGeneratedRiskScore')) {
        obj['AiGeneratedRiskScore'] = ApiClient.convertToType(data['AiGeneratedRiskScore'], 'Number');
      }
      if (data.hasOwnProperty('AiSource')) {
        obj['AiSource'] = ApiClient.convertToType(data['AiSource'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if the image is clean (not AI generated) and false otherwise
   * @member {Boolean} CleanResult
   */
  exports.prototype['CleanResult'] = undefined;
  /**
   * Risk score between 0.0 (no risk) and 1.0 (highest risk), with anything over 0.8 being high risk
   * @member {Number} AiGeneratedRiskScore
   */
  exports.prototype['AiGeneratedRiskScore'] = undefined;
  /**
   * Tool used to generate the image, if identified (this cannot always be identified)
   * @member {String} AiSource
   */
  exports.prototype['AiSource'] = undefined;



  return exports;
}));


